title: Согласование процесса
description: 
  'Рассказали в деталях, как устроен процесс согласования в Stormbpmn: на какие сообщения ориентироваться, как оставлять комментарии на диаграмме, как составить резолюцию и отправить процесс на доработку.'
version: 2
status: new
tags:
  - Согласование и обсуждение