title: Работа со слоями видимости в редакторе диаграмм (Overlay)
description: 'Руководство по работе с оверлеями в редакторе диаграмм Stormbpmn: как включать и отключать слои видимости, отображать ошибки и задавать настройки по умолчанию.'
version: 2