title: Создание, изменение, удаление бизнес-процессов
summary: 'Статья показывает, как создавать бизнес-процессы в дереве и каталоге, добавлять дочерние и переиспользуемые процессы и работать с карточкой процесса и ее вкладками.'
plan: '- Team<br>- Business<br>'
tags:
  - Процессная архитектура, реестр бизнес-процессов