title: 'Мастер-класс: моделируем процессы Stormbpmn в Stormbpmn'
desc: 'Мастер‑класс по практическому применению BPMN: создание верхнеуровневых карт, детальная проработка процесса «от лида до договора» и приёмы работы аналитика для эффективного онбординга.'
version: 2
