title: Отправка процесса на согласование
description:
  'Показываем наглядно процесс согласования диаграммы с ревьюерами: отправка уведомлений, изменение статуса диаграммы, согласование, завершение процесса ревью.'
status: new
version: 2
tags:
  - Согласование и обсуждение