title: Работа с версионированием процессов
description:
  Рассказываем как работать с версионированием процессов в Stormbpmn. 
  Вы узнаете как создавать версии процессов, как из них восстанавливать процесс 
  и как работает автосохранение версий.
tags:
  - Спецфичи редактора BPMN
status: new
version: 2
plan:
  - Team
  - Business
permissions: 
  - ADMIN
roles:
  - Администратор команды

